# frozen_string_literal: true

class AddDeleteCascadeToForeignKeys < ActiveRecord::Migration[5.2]
  def up
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_commit_id FOREIGN KEY (commit_id) REFERENCES commits(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_request_id FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_pull_request_id FOREIGN KEY (pull_request_id) REFERENCES pull_requests(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE builds ADD CONSTRAINT fk_new_builds_on_config_id FOREIGN KEY (config_id) REFERENCES build_configs(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE jobs ADD CONSTRAINT fk_new_jobs_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE jobs ADD CONSTRAINT fk_new_jobs_on_commit_id FOREIGN KEY (commit_id) REFERENCES commits(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE jobs ADD CONSTRAINT fk_new_jobs_on_stage_id FOREIGN KEY (stage_id) REFERENCES stages(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE jobs ADD CONSTRAINT fk_new_jobs_on_config_id FOREIGN KEY (config_id) REFERENCES job_configs(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE branches ADD CONSTRAINT fk_new_branches_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE tags ADD CONSTRAINT fk_new_tags_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE commits ADD CONSTRAINT fk_new_commits_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE commits ADD CONSTRAINT fk_new_commits_on_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE commits ADD CONSTRAINT fk_new_commits_on_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE crons ADD CONSTRAINT fk_new_crons_on_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE job_configs ADD CONSTRAINT fk_new_job_configs_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE build_configs ADD CONSTRAINT fk_new_build_configs_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE pull_requests ADD CONSTRAINT fk_new_pull_requests_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE ssl_keys ADD CONSTRAINT fk_new_ssl_keys_on_repository_id FOREIGN KEY (repository_id) REFERENCES repositories(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE requests ADD CONSTRAINT fk_new_requests_on_commit_id FOREIGN KEY (commit_id) REFERENCES commits(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE requests ADD CONSTRAINT fk_new_requests_on_pull_request_id FOREIGN KEY (pull_request_id) REFERENCES pull_requests(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE requests ADD CONSTRAINT fk_new_requests_on_branch_id FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE requests ADD CONSTRAINT fk_new_requests_on_tag_id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE requests ADD CONSTRAINT fk_new_requests_on_config_id FOREIGN KEY (config_id) REFERENCES request_configs(id) ON DELETE CASCADE NOT VALID'
    execute 'ALTER TABLE stages ADD CONSTRAINT fk_new_stages_on_build_id FOREIGN KEY (build_id) REFERENCES builds(id) ON DELETE CASCADE NOT VALID'

    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_repository_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_commit_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_request_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_pull_request_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_branch_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_tag_id'
    execute 'ALTER TABLE builds VALIDATE CONSTRAINT fk_new_builds_on_config_id'
    execute 'ALTER TABLE jobs VALIDATE CONSTRAINT fk_new_jobs_on_repository_id'
    execute 'ALTER TABLE jobs VALIDATE CONSTRAINT fk_new_jobs_on_commit_id'
    execute 'ALTER TABLE jobs VALIDATE CONSTRAINT fk_new_jobs_on_stage_id'
    execute 'ALTER TABLE jobs VALIDATE CONSTRAINT fk_new_jobs_on_config_id'
    execute 'ALTER TABLE branches VALIDATE CONSTRAINT fk_new_branches_on_repository_id'
    execute 'ALTER TABLE tags VALIDATE CONSTRAINT fk_new_tags_on_repository_id'
    execute 'ALTER TABLE commits VALIDATE CONSTRAINT fk_new_commits_on_repository_id'
    execute 'ALTER TABLE commits VALIDATE CONSTRAINT fk_new_commits_on_branch_id'
    execute 'ALTER TABLE commits VALIDATE CONSTRAINT fk_new_commits_on_tag_id'
    execute 'ALTER TABLE crons VALIDATE CONSTRAINT fk_new_crons_on_branch_id'
    execute 'ALTER TABLE job_configs VALIDATE CONSTRAINT fk_new_job_configs_on_repository_id'
    execute 'ALTER TABLE build_configs VALIDATE CONSTRAINT fk_new_build_configs_on_repository_id'
    execute 'ALTER TABLE pull_requests VALIDATE CONSTRAINT fk_new_pull_requests_on_repository_id'
    execute 'ALTER TABLE ssl_keys VALIDATE CONSTRAINT fk_new_ssl_keys_on_repository_id'
    execute 'ALTER TABLE requests VALIDATE CONSTRAINT fk_new_requests_on_commit_id'
    execute 'ALTER TABLE requests VALIDATE CONSTRAINT fk_new_requests_on_pull_request_id'
    execute 'ALTER TABLE requests VALIDATE CONSTRAINT fk_new_requests_on_branch_id'
    execute 'ALTER TABLE requests VALIDATE CONSTRAINT fk_new_requests_on_tag_id'
    execute 'ALTER TABLE requests VALIDATE CONSTRAINT fk_new_requests_on_config_id'
    execute 'ALTER TABLE stages VALIDATE CONSTRAINT fk_new_stages_on_build_id'

    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_repository_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_commit_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_request_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_pull_request_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_branch_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_tag_id'
    execute 'ALTER TABLE builds DROP CONSTRAINT fk_builds_on_config_id'
    execute 'ALTER TABLE jobs DROP CONSTRAINT fk_jobs_on_repository_id'
    execute 'ALTER TABLE jobs DROP CONSTRAINT fk_jobs_on_commit_id'
    execute 'ALTER TABLE jobs DROP CONSTRAINT fk_jobs_on_stage_id'
    execute 'ALTER TABLE jobs DROP CONSTRAINT fk_jobs_on_config_id'
    execute 'ALTER TABLE branches DROP CONSTRAINT fk_branches_on_repository_id'
    execute 'ALTER TABLE tags DROP CONSTRAINT fk_tags_on_repository_id'
    execute 'ALTER TABLE commits DROP CONSTRAINT fk_commits_on_repository_id'
    execute 'ALTER TABLE commits DROP CONSTRAINT fk_commits_on_branch_id'
    execute 'ALTER TABLE commits DROP CONSTRAINT fk_commits_on_tag_id'
    execute 'ALTER TABLE crons DROP CONSTRAINT fk_crons_on_branch_id'
    execute 'ALTER TABLE job_configs DROP CONSTRAINT fk_job_configs_on_repository_id'
    execute 'ALTER TABLE build_configs DROP CONSTRAINT fk_build_configs_on_repository_id'
    execute 'ALTER TABLE pull_requests DROP CONSTRAINT fk_pull_requests_on_repository_id'
    execute 'ALTER TABLE ssl_keys DROP CONSTRAINT fk_ssl_keys_on_repository_id'
    execute 'ALTER TABLE requests DROP CONSTRAINT fk_requests_on_commit_id'
    execute 'ALTER TABLE requests DROP CONSTRAINT fk_requests_on_pull_request_id'
    execute 'ALTER TABLE requests DROP CONSTRAINT fk_requests_on_branch_id'
    execute 'ALTER TABLE requests DROP CONSTRAINT fk_requests_on_tag_id'
    execute 'ALTER TABLE requests DROP CONSTRAINT fk_requests_on_config_id'
    execute 'ALTER TABLE stages DROP CONSTRAINT fk_stages_on_build_id'

    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_repository_id TO fk_builds_on_repository_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_commit_id TO fk_builds_on_commit_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_request_id TO fk_builds_on_request_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_pull_request_id TO fk_builds_on_pull_request_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_branch_id TO fk_builds_on_branch_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_tag_id TO fk_builds_on_tag_id'
    execute 'ALTER TABLE builds RENAME CONSTRAINT fk_new_builds_on_config_id TO fk_builds_on_config_id'
    execute 'ALTER TABLE jobs RENAME CONSTRAINT fk_new_jobs_on_repository_id TO fk_jobs_on_repository_id'
    execute 'ALTER TABLE jobs RENAME CONSTRAINT fk_new_jobs_on_commit_id TO fk_jobs_on_commit_id'
    execute 'ALTER TABLE jobs RENAME CONSTRAINT fk_new_jobs_on_stage_id TO fk_jobs_on_stage_id'
    execute 'ALTER TABLE jobs RENAME CONSTRAINT fk_new_jobs_on_config_id TO fk_jobs_on_config_id'
    execute 'ALTER TABLE branches RENAME CONSTRAINT fk_new_branches_on_repository_id TO fk_branches_on_repository_id'
    execute 'ALTER TABLE tags RENAME CONSTRAINT fk_new_tags_on_repository_id TO fk_tags_on_repository_id'
    execute 'ALTER TABLE commits RENAME CONSTRAINT fk_new_commits_on_repository_id TO fk_commits_on_repository_id'
    execute 'ALTER TABLE commits RENAME CONSTRAINT fk_new_commits_on_branch_id TO fk_commits_on_branch_id'
    execute 'ALTER TABLE commits RENAME CONSTRAINT fk_new_commits_on_tag_id TO fk_commits_on_tag_id'
    execute 'ALTER TABLE crons RENAME CONSTRAINT fk_new_crons_on_branch_id TO fk_crons_on_branch_id'
    execute 'ALTER TABLE job_configs RENAME CONSTRAINT fk_new_job_configs_on_repository_id TO fk_job_configs_on_repository_id'
    execute 'ALTER TABLE build_configs RENAME CONSTRAINT fk_new_build_configs_on_repository_id TO fk_build_configs_on_repository_id'
    execute 'ALTER TABLE pull_requests RENAME CONSTRAINT fk_new_pull_requests_on_repository_id TO fk_pull_requests_on_repository_id'
    execute 'ALTER TABLE ssl_keys RENAME CONSTRAINT fk_new_ssl_keys_on_repository_id TO fk_ssl_keys_on_repository_id'
    execute 'ALTER TABLE requests RENAME CONSTRAINT fk_new_requests_on_commit_id TO fk_requests_on_commit_id'
    execute 'ALTER TABLE requests RENAME CONSTRAINT fk_new_requests_on_pull_request_id TO fk_requests_on_pull_request_id'
    execute 'ALTER TABLE requests RENAME CONSTRAINT fk_new_requests_on_branch_id TO fk_requests_on_branch_id'
    execute 'ALTER TABLE requests RENAME CONSTRAINT fk_new_requests_on_tag_id TO fk_requests_on_tag_id'
    execute 'ALTER TABLE requests RENAME CONSTRAINT fk_new_requests_on_config_id TO fk_requests_on_config_id'
    execute 'ALTER TABLE stages RENAME CONSTRAINT fk_new_stages_on_build_id TO fk_stages_on_build_id'
  end

  def down; end
end
