version: '3'

services:
  postgres_travis_migrations:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'travis_test'
    ports:
      - '5431:5432'
    volumes:
      - './.db_travis_test:/var/lib/postgresql/data'
