source 'https://rubygems.org'

gem 'activerecord', '~> 4.2'
gem 'pg', '~> 0.18'
gem 'rake', '~> 10.4'
gem 'micro_migrations', '~> 0.0'
gem 'data_migrations', '~> 0.0'
gem 'bundler', '~> 1.7'
gem 'rspec', '~>3.4'
gem 'rails_12factor'
