# This is only used for standalone_migrations. In other contexts
# Travis.config.database will be used.

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost/travis_production') %>

development:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost/travis_development') %>

pro_development:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost/travis_pro_development') %>

test:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost/travis_test') %>

pro_test:
  <<: *defaults
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost/travis_pro_test') %>
