#!/bin/bash

set -ev

docker-compose build migrations;

docker login -u=$QUAY_ROBOT_HANDLE -p=$QUAY_ROBOT_TOKEN quay.io;

docker images;

docker tag travismigrations_migrations quay.io/travisci/travis-migrations:$TRAVIS_BRANCH;
docker push quay.io/travisci/travis-migrations:$TRAVIS_BRANCH;

docker tag travismigrations_migrations quay.io/travisci/travis-migrations:${TRAVIS_COMMIT:0:7};
docker push quay.io/travisci/travis-migrations:${TRAVIS_COMMIT:0:7};

if [ ${TRAVIS_BRANCH} = "master" ]; then
  docker tag travismigrations_migrations quay.io/travisci/travis-migrations:latest";
  docker push quay.io/travisci/travis-migrations:$TRAVIS_BRANCH";
fi

exit 0;
